- block:
    - name: "12.1 :: Check auth status"
      include: "cj-auth_check.yml"

    - name: "12.2 :: Cli Login"
      include: "cj-cli-login.yml"

    - name: "12.3 :: Demo seed job(s) - if requested login, delete, import & trigger 1st build"
      include: "cj-seed.yml"
    when: ((cj_seed_demo is defined) and (cj_seed_demo | bool))
